# Generated by Django 5.0 on 2024-01-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais_origen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.pais', verbose_name='país de origen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='automovil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.auto', verbose_name='auto'),
        ),
    ]
