# Generated by Django 5.0.1 on 2024-01-17 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('fecha_actualizacion', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de actualización')),
                ('categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.productocategoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
